### ISSUE TITLE
Login Dialog Box opens and closes automatically

### ISSUE THREAD

**Issue by susarlanikhilesh** [alekseynemiro/Nemiro.OAuth.LoginForms#11]
obj.ShowDialog() //is the function call

This issue we are facing in a particular Microsoft Surface Pro device. The dialog box appears and closes automatically. Does not wait for the user input for username and password. 

Can you please help us with this?

Thank you.
Susarla Nikhilesh.

**Comment by KyrXtz** [comment]
Same issue here, did you find a solution?

**Comment by susarlanikhilesh** [comment]
@KyrXtz We didn't. We instead wrote our own oauth with ui and used.
Thank you.

**Comment by chicly** [comment]
me also same issue

**Comment by susarlanikhilesh** [comment]
Hi,

We didn't find a solution either. We instead wrote our own application for
it.

Thank you.
Susarla Nikhilesh

**Comment by chicly** [comment]
first use dll file same problem occur so that download nemiro.auth.loginform project added my project to occur same issue how to solve.

**Comment by chicly** [comment]
Now it's work
