### ISSUE TITLE
Как насторить приложение

### ISSUE THREAD

**Issue by Luonic** [alekseynemiro/Nemiro.OAuth.LoginForms#2]
Я хочу авторизоваться в Тамблере, но не понятно, какой callback url необходимо прописать, чтобы получать токен. Так как приложение WinForms, я не могу прописать адрес своего сайта, потому что его нет.

**Comment by alekseynemiro** [comment]
Использовать **localhost**, либо сделать любую пустую страничку на любом сайте, типа: http://oauthproxy.nemiro.net/

Для **Windows Forms** можно хоть адрес **Google** указать :-) Главное убедиться, что параметры не будут удалятся. Маркер доступа будет находиться в адресе страницы и чтобы его извлечь, страница должна успешно загрузиться. Стандартный **WebBrowser** (**Internet Explorer**), который используется для форм авторизации, может не сохранить исходный адрес, если страница будет недоступна. 

В случае с указанием адреса, над которым нет контроля, есть риск утечки данных, да и визуализировать процесс придется как-то. Например, если указать обратный адрес https://www.google.ru/, то наверняка, при получении маркера доступа сайт **Google** мелькнет в окошке, что может сбить столку пользователя.

Лучше свою страничку сделать. Можно на любом бесплатном хостинге это сделать. Либо использовать любой свой сайт, если есть. 

Адрес http://oauthproxy.nemiro.net/ тоже можно использовать, я не планирую с ним ничего делать.
