### ISSUE TITLE
failed to update twitter status

### ISSUE THREAD

**Issue by serhiy1994** [alekseynemiro/Nemiro.OAuth.LoginForms#3]
I can log in Twitter and get the access token with your library & login forms (thanks!), but can't update my status (i.e. tweet). Why?
private void PostUpdateStatus()
        {
            this.Cursor = Cursors.WaitCursor;
            var parameters = new HttpParameterCollection();
            parameters.AddUrlParameter("status", this.textBox3.Text);
            parameters.AddUrlParameter("oauth_consumer_key", this.ConsumerKey);
            parameters.AddUrlParameter("oauth_consumer_secret", this.ConsumerSecret);
            parameters.AddUrlParameter("oauth_token", Properties.Settings.Default.TwitterToken);
            parameters.AddUrlParameter("oauth_token_secret", Properties.Settings.Default.TwitterSecret);
            OAuthUtility.GetAsync
            (
              "https://api.twitter.com/1.1/statuses/update.json",
                parameters: parameters,
              authorization: this.GetAuth(),
              callback: PostUpdateStatus_Result
            );
        }

**Comment by alekseynemiro** [comment]
Use **POST** method: OAuthUtility.**PostAsync**(...)

And also **multipart/form-data** content type.

```C#
OAuthUtility.PostAsync
(
  "https://api.twitter.com/1.1/statuses/update.json",
  parameters: parameters,
  authorization: this.GetAuth(),
  callback: PostUpdateStatus_Result,
  contentType: "multipart/form-data"
);
```

**Comment by serhiy1994** [comment]
Спасибо большое, теперь благодаря вам я смогу защитить диплом! :3
