### ISSUE TITLE
Problem with Dropbox login dialogue

### ISSUE THREAD

**Issue by ejazgithub** [alekseynemiro/Nemiro.OAuth.LoginForms#4]
Cant login after login press
I think login button is not working
i have attached the screenshot...take a look on it.
![dropboxfailed](https://cloud.githubusercontent.com/assets/19358426/17697579/455f2e7c-63d3-11e6-8d6f-cf20be775362.png)

**Comment by alekseynemiro** [comment]
I do not see a problems. I have everything working correctly.
* Windowx 7 x64
* Internet Explorer 11
* Nemiro.OAuth.LoginForms v1.4.4.2483

**Comment by ejazgithub** [comment]
Yes its working fine after updating the IE8  to IE11,
thank you so much you saved my life.

**Comment by chicly** [comment]
me also same problem
