### ISSUE TITLE
Cannot use accesstokenvalue from LiveLogin

### ISSUE THREAD

**Issue by shomarisharpe** [alekseynemiro/Nemiro.OAuth.LoginForms#5]
the access token returned from a livelogin form does not work with the latest onedrive sdk

**Comment by alekseynemiro** [comment]
You are using a scope?

https://dev.onedrive.com/auth/msa_oauth.htm#authentication-scopes
<table>
<thead>
<tr>
	<th align="left">Scope name</th>
	<th align="left">Description</th>
	<th align="left">Required</th>
</tr>
</thead>
<tbody>
<tr>
	<td align="left">offline_access</td>
	<td align="left">Enables your app to work offline even when the user isn't active. This provides your app with a refresh_token that can be used to generate additional access tokens as necessary. This scope is not available for token flow.</td>
	<td align="left">No</td>
</tr>
<tr>
	<td align="left">onedrive.readonly</td>
	<td align="left">Grants read-only permission to all of a user's OneDrive files, including files shared with the user.</td>
	<td align="left">Yes</td>
</tr>
<tr>
	<td align="left">onedrive.readwrite</td>
	<td align="left">Grants read and write permission to all of a user's OneDrive files, including files shared with the user. To create sharing links, this scope is required.</td>
	<td align="left">Yes</td>
</tr>
<tr>
	<td align="left">onedrive.appfolder</td>
	<td align="left">Grants read and write permissions to a specific folder for your application.</td>
	<td align="left">Yes</td>
</tr>
</tbody>
</table>

```C#
var login = new LiveLogin
(
  "000000004C1337C9", 
  "7N3IwTyTGoGGimndiJAQiG2GBspOLyFZ", 
  "http://oauthproxy.nemiro.net/",
  "onedrive.readwrite"
);
```
