### ISSUE TITLE
ILoginForm interface should be public

### ISSUE THREAD

**Issue by austin-----** [alekseynemiro/Nemiro.OAuth.LoginForms#6]
ILoginForm should be public so that new classes can derive from Login and implement WebDocumentLoad() for different handlings. Currently the interface is internal.

**Comment by alekseynemiro** [comment]
I will think about it. 

At the moment, you can use the source code "as is" in own projects. The code is simple. And you can remove all unnecessary.

Thank you for message!

**Comment by alekseynemiro** [comment]
v1.6 released!

Now `ILoginForm` is public.
