### ISSUE TITLE
Login in Dropbox with different users failed

### ISSUE THREAD

**Issue by ed-miller** [alekseynemiro/Nemiro.OAuth.LoginForms#7]
Hi,

I created an Dropbox account and login through Nemiro.OAuth.LoginForms. This works fine the first time. 
But then I try to login again or when I login with other account on same computer, the OAuth.LoginForms
leads me simply back to auth screen.

Google and Microsoft Live are working fine.

**Comment by alekseynemiro** [comment]
Yes, I can see some problems with **autoLogout** option in **Dropbox**. 
Try not to use this option for the **Dropbox**. Maybe it will work as expected.

I need time to find the causes of the problem.
Thank you for message!

**Comment by alekseynemiro** [comment]
v1.6 released!

Dropbox fixed.

**Comment by ed-miller** [comment]
Great! Thank you!
